config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'

  devise_for :users
  resources :products do
    resources :carts, only: [:create, :destroy]
    resources :cart_products, only: [:create, :destroy]
  end
  resources :carts, only: [:index, :destroy]
  resources :orders, only: [:index, :create]
  resources :users, only: [:show, :update]
  resources :admins, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user

  has_many :cart_products, dependent: :destroy
  has_many :products, through: :cart_products

  # after_create :validated_cart

  def validated_cart
    UserMailer.validated_cart_email(user).deliver_now
  end

  def empty
    CartProduct.where(cart_id: self.id).destroy_all
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user
  
  def create
    @product = Product.find(params[:product_id])
    @cart = Cart.new(
      product: @product,
      user: current_user,
      quantity: 1
    )

    respond_to do |format|
      if @cart.save
        format.html {
          redirect_back fallback_location: root_path,
            notice: 'Ajouté au panier !'
        }
      else
        format.html {
          redirect_back fallback_location: root_path
        }
      end
    end
  end

  def destroy
    current_user.cart.empty
    respond_to do |format|
      format.html {
        redirect_back fallback_location: root_path
      }
    end
  end

  def index
    @carts = Cart.where(user: current_user)
    @user = current_user
    #@products =
  end

  def authenticate_user
    if !user_signed_in?
      flash[:info] = "Connecte toi avant !"
      redirect_back(fallback_location: :root)
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_stripe.html.erb
<%= form_tag orders_path, method: :post do %>             <%# Modifier le path  pour supprimer la carte et créer un order%>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
  </article>
  <div class="form-group">
    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
      data-description="Payer mon panier"
      data-amount= "<%= amount %>"
      data-currency = "eur"
      data-locale="auto"
      data-label="Payer par carte : <%= amount.to_f / 100%>€"></script>
  </div>
<% end %>

app/views/carts/index.html.erb
<%= render "products/cards", products: current_user.carted_products %>

<div id="stripe_btn">
  <% if current_user.total_cart_price != 0 %>
    <%= render 'stripe', amount: current_user.total_cart_price %>
  <% end %>
</div>
<div class="w-100" id="accordion">
  <%= render "users/ordered_products_list"%>
</div>