config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'

  devise_for :users
  resources :products do
    resources :carts, only: [:create, :destroy]
    resources :cart_products, only: [:create, :destroy]
  end
  resources :carts, only: [:index, :destroy]
  resources :orders, only: [:index, :create]
  resources :users, only: [:show, :update]
  resources :admins, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true, length: { in: 2..140 }
  validates :description, length: { in: 0..1000}
  validates :price, presence: true, numericality: { greather_than_or_equal_to: 0, less_than_or_equal_to: 10000 }
  #validates :image_url, presence: true

  has_many :cart_products, dependent: :destroy
  has_many :carts, through: :cart_products, source: :cart
  has_many :buyers, through: :carts, source: :user

  has_many :order_products, dependent: :destroy
  has_many :orders, through: :order_products, source: :order
  has_many :owners, through: :orders, source: :user

  has_one_attached :image


  def price_in_euro
    return "%0.2f" % (self.price/100.00) + "€"
  end

  def image_handler
    if self.image.attached?
      return self.image
    else
      return "missing.png"
    end
  end

  def get_cart(user)
    carts = Cart.where(user:user).first
  end

  def in_cart?(user)
    carts = CartProduct.where("cart_id = ? AND product_id = ?", user.cart.id, self)
    if carts.length == 0
      return false
    else
      return true
    end
  end

  def add_to_cart(user)
    Cart.create(
      product: self,
      user: user,
      quantity: 1
    )
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :user_is_admin, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    #@product.image.attach(params[:product][:image])

    respond_to do |format|
      if @product.save
        format.html { redirect_to admins_path, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to admins_path, notice: 'Product was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admins_path, notice: 'Product was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :image)
    end

    def user_is_admin
      redirect_to root_path unless current_user.admin
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_add_remove_product_button.erb
<% if !product.in_cart?(current_user) %>

  <%= link_to product_cart_products_path(product), 
              class: "btn btn-primary",
              id: "add-product-#{product.id}",
              method: :post,
              remote: true do %>
    <i class="fa fa-cart-plus"></i>
    Ajouter au panier
  <% end %>

<% else %>

  <%= link_to product_cart_product_path(product_id: product.id, id: current_user.cart_product(product).id),
              method: :delete,
              id: "add-product-#{product.id}",
              class: "btn btn-primary",
              remote: true do %>
    <i class="fa fa-trash-alt"></i>
    Enlever du panier
  <% end %>

<% end %>

app/views/products/_cards.html.erb
<div class="ml-2 mr-2">
  <div class="row justify-content-center">
    <% products.each_with_index do |product, index| %>
        <div class="card col-2 m-2 product-item">
          <div class="h-100">
          <%= link_to product do %>
              <%= image_tag product.image_handler,
              class: "card-img-top img-fluid",
              alt: "photo_" + product.name%>
          <% end %>
        </div>
          <div class="card-body product_info">
            <h6 class="card-title"><%= link_to product.name, product %></h6>
            <div class="product_price ml-auto mr-auto">
              <%= (product.price_in_euro)  %>
            </div>
          </div>
          
          <% if user_signed_in? %>
            <%= render 'products/add_remove_product_button', product: product %>
          <% end %>

        </div>
    <% end %>
  </div>
</div>

app/views/products/_form.html.erb
<div class="">

  <%= form_with(model: product, local: true, multipart: true) do |form| %>
    <% if product.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class:"form-control" %>
    </div>

    <div class="field form-group">
      <%= form.label :description %>
      <%= form.text_area :description, class:"form-control" %>
    </div>

    <div class="field form-group">
      <%= form.label :price %>
      <%= form.number_field :price, class:"form-control" %>
    </div>

    <div class="field form-group">
      <%= form.label :image %>
      <%= form.file_field :image,
      accept: 'image/png,image/jpeg,image/gif',
      class:"" %>
    </div>

    <div class="actions">
      <%= form.submit class:"btn btn-primary" %>
    </div>
  <% end %>

</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Notre catalogue</h1>


<%= render "cards", products: @products %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <%= @product.name %>
</h2>

<%= image_tag @product.image_handler,
class: "preview",
alt: "photo_" + @product.name %>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Prix:</strong>
  <%= @product.price_in_euro %>
</p>

<% if user_signed_in? %>
  <%= render 'add_remove_product_button', product: @product %>
<% end %>