config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'

  devise_for :users
  resources :products do
    resources :carts, only: [:create, :destroy]
    resources :cart_products, only: [:create, :destroy]
  end
  resources :carts, only: [:index, :destroy]
  resources :orders, only: [:index, :create]
  resources :users, only: [:show, :update]
  resources :admins, only: [:index]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_cdn.html.erb
	<!-- FONTAWESOME -->

	<link rel="stylesheet"

	href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"

	integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay"

	crossorigin="anonymous">



	<!-- BOOTSTRAP -->

	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"

	integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"

	crossorigin="anonymous"></script>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"

	integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"

	crossorigin="anonymous"></script>

	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"

	integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"

	crossorigin="anonymous"></script>

app/views/layouts/_flashs.html.erb
<%# Display each flash alert %>
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

app/views/layouts/_nav_span.html.erb
    <%= current_user.carted_products.count %>

app/views/layouts/_navbar.html.erb
<!-- Main Navigation -->

		<div class="main_nav_container">
			<div class="container">
				<div class="row">
					<div class="col-lg-12 text-right">
						<div class="logo_container">
							<%= link_to root_path do %>
								E<span>kitty</span>
							<% end %>
						</div>
						<nav class="navbar">
							<ul class="navbar_menu">
								<li>
									<%= link_to products_path do %>
										Catalogue
									<% end %>
								</li>
							</ul>

							<ul class="navbar_user">


								<% if user_signed_in? && current_user.admin %> <!--&& user.is_admin?-->
									<li class="">
										<%= link_to admins_path do %>
											<i class="fa fa-cog" aria-hidden="true"></i>
										<% end %>
									</li>
								<% end %>

								<li>
									<div class="dropdown show">
									  <a class="dropdown-toggle"
										href="#" role="button" id="dropdownMenuLink"
										data-toggle="dropdown" aria-haspopup="true"
										aria-expanded="false">
									    <i class="fa fa-user" aria-hidden="true"></i>
									  </a>

									  <div class="dropdown-menu dropdown-menu-right"
										aria-labelledby="dropdownMenuLink">
											<% if user_signed_in? %>
												<%= link_to 'Log out', destroy_user_session_path, method: :delete %>
												<%= link_to 'Edit info', user_path(current_user) %>
											<% else %>
												<%= link_to 'Log in', new_user_session_path %>
												<%= link_to 'Sign up', new_user_registration_path %>
											<% end %>
									  </div>
									</div>
								</li>

								<% if user_signed_in? %>
									<li class="checkout">
										<%= link_to carts_path do %>
											<i class="fa fa-shopping-cart" id="nb_checkout_items" aria-hidden="true"></i>

											<% if current_user && current_user.carted_products.count > 0 %> <%# article? display ! %>
												<span id="checkout_items" class="checkout_items" style="display: block;">
													<%= current_user.carted_products.count %>
												</span>
                      <% else %> <%# no article, no display %>
                        <span id="checkout_items" class="checkout_items" style="display: none;">
													<%= current_user.carted_products.count %>
												</span>
											<% end %>
                      
										<% end %>
									</li>
								<% end %>

							</ul>
							<div class="hamburger_container">
								<i class="fa fa-bars" aria-hidden="true"></i>
							</div>
						</nav>
					</div>
				</div>
			</div>
		</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EKitty</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= render "layouts/cdn.html.erb" %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render 'layouts/navbar' %>

      <%# Display each flash alert %>
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>

    <%= yield %>

  </body>
</html>